vich_uploader:
    db_driver: orm
    
    mappings:
        container_image:
            uri_prefix: /images/containers
            upload_destination: '%kernel.project_dir%/public/images/containers'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
